language: objective-c

install:
  - bundle install --without=documentation --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec slather setup Heliograph.xcodeproj

xcode_project: Heliograph.xcodeproj
xcode_scheme: Heliograph

cache:
  - bundler

after_success:
  - bundle exec slather

