language: objective-c

install:
  - bundle install --without=documentation --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec slather setup OpinionatedC-Mirrors.xcodeproj

xcode_project: OpinionatedC-Mirrors.xcodeproj
xcode_scheme: OpinionatedC-Mirrors

cache:
  - bundler

after_success:
  - bundle exec slather

